server.port: ${SERVER_PORT:8080}

spring.h2.console.enabled: true

logging.level.org.springframework: INFO
logging.level.org.springframework.jdbc.core: TRACE
logging.level.ru.notebot: trace


#spring.datasource.url: jdbc:mysql://localhost:3306/springjdbc
#spring.datasource.username: guest_user
#spring.datasource.password: guest_password